Update import.mdx to reflect the need for both an authenticated and unauthenticated role with trust relationship to the imported Identity Pool (#4531)
Issue #, if available:

To import an existing Identity Pool into Amplify Auth, both an authenticated role and unauthenticated role with trust relationship to the Identity Pool are required. Without that, the following error occurs in Amplify Studio and Amplify CLI:

Cannot import Identity Pool without roles.
Error: Cannot import Identity Pool without roles.

For more information see this Stack Overflow post I wrote on this:
https://stackoverflow.com/a/73366873/9700687

*Description of changes:*
Change the Import.mdx doc page to reflect this.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.