Resolve Typescript validation check failed
The hander definition previously didn't include a type so the "npx ampx sandbox" compilation would fail and say:
amplify/functions/say-hello/handler.ts(1,31): error TS7006: Parameter 'event' implicitly has an 'any' type.
TypeScript validation check failed.
Resolution: Fix the syntax and type errors in your backend definition.